apiVersion: apps/v1
kind: Deployment
metadata:
  name: faust
spec:
  selector:
    matchLabels:
      app: faust
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: faust
    spec:
      containers:
      - name: faust
        image: gcr.io/kafka-streaming-tests/kafka-streaming-py
        command: ["python", "python/streaming/streaming_faust.py", "worker", "--loglevel",
                  "info"]
#        imagePullPolicy: Never
        resources:
          requests:
            memory: 0.1G
            cpu: "0.2"
          limits:
            memory: 0.5G
            cpu: "1"
        env:
        - name: LOG_LEVEL
          value: "ERROR"
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-configs
              key: input_topic
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-configs
              key: output_topic
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-configs
              key: bootstrap_servers
        - name: CONCURRENCY
          value: "100"
        - name: MAX_INFERENCE_TIME_MS
          value: "50"
